### ISSUE TITLE
Export to Image

### ISSUE THREAD

**Issue by Semyazz** [niloch/iplotter#4]
Some tips how can I export images to static files? It's nice to use the same library in HTML interactive reports and in PDF version, but in PDF I need static images (e.g. SVG, PNG).

**Comment by niloch** [comment]
I've been looking at using `pdfkit` with `wkhtmltopdf` but haven't had success yet getting the javascript to render correctly.  I've done screenshots or print-to-pdf,  but so far haven't found a good solution for  programmatically saving a non-HTML version.  I'll keep looking into it.
